// ─────────────────────────────────────────────────────────────────────────
// Design System da Conversão Extrema — biblioteca de componentes (React)
// Importe tudo a partir daqui: import { Button, Card, ... } from './components/ui'
// ─────────────────────────────────────────────────────────────────────────
export { Container, Section, Eyebrow, SectionHeader, Stars } from './primitives'
export { Display, Heading, Text, Code, Kbd, Link } from './Typography'
export { Button, ButtonIconBadge } from './Button'
export { Badge } from './Badge'
export { Breadcrumbs } from './Breadcrumbs'
export { Card, FeatureIconCard, MediaCard } from './Card'
export { MetricCard } from './MetricCard'
export { Field, Input } from './Input'
export { Select } from './Select'
export { DateInput, DateRangeField } from './DateField'
export { SegmentedControl } from './SegmentedControl'
export { TestimonialCard, VideoTestimonialCard } from './Testimonial'
export { PricingCard } from './Pricing'
export { Faq } from './Faq'
export { Stats } from './Stats'
export { Table } from './Table'
export { SidebarNav } from './SidebarNav'
export { Navbar } from './Navbar'
export { Footer } from './Footer'
export { Logo } from './Logo'
export { ThemeToggle, useTheme } from './ThemeToggle'
export { FadeIn } from './FadeIn'
export { HoverHeadline } from './HoverHeadline'
export { MembersPortalMockup } from './MembersPortalMockup'
export { SolutionShowcase } from './SolutionShowcase'
export { Marquee } from './Marquee'
export { DotGrid } from './DotGrid'
export { VideoLightbox } from './VideoLightbox'
export { VideoModal } from './VideoModal'
export { useSpotlight } from '../../lib/useSpotlight'
